---
version: "{build}"
branches:
  only:
    - master
clone_depth: 10
install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby --version
  - gem --version
  - gem install bacon
  - mkdir tmp

build: off
test_script:
  - bacon -a
after_test:

environment:
  matrix:
    - ruby_version: "200"
    - ruby_version: "21"
    - ruby_version: "22"